# Actividad 1 - Identificación de la fuente



Cita de la fuente: 
United Nations, World Population Prospects (2024)

UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

Preguntas:
¿Quién produjo originalmente los datos? La unión europea en el 2024.

¿Qué organización los procesa para su utilización en Our World in Data? Según sus archivos, los datos provienen de diferentes proveedores u organizaciones, por lo que no existe una única eorganización encargada de procesarlos para ser utilizados posteriormente.

¿Qué representa la variable que analizarás?

# Actividad 2 - Carga y exploración de datos.

In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [2]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [3]:
df.shape

(38400, 5)

In [4]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [5]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [6]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [7]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [8]:
df["Entity"].nunique()

256

# Preguntas - Actividad 2: 
¿Cuántas filas y columnas tiene el dataset? Tiene 38400 filas y 5 columnas.

¿Qué tipo de datos contiene la variable "year"? De tipo int.

¿Existen valores faltantes? Sí, las columnas Code, Annual change in population y Annual population change (projected). 

¿Cuántas entidades diferentes contiene el dataset? 256.

# Actividad 3 - Estadística descriptiva

In [9]:
F_pais =df.loc[(df["Entity"] == "Portugal") & (df["Year"] >= 2006) & (df["Year"] <= 2020), "Annual change in population" ]

print("Media:", F_pais.mean())
print("Mediana:", F_pais.median())
print("Desviación Estándar:", F_pais.std())
print("Mínimo:", F_pais.min())
print("Máximo:", F_pais.max())

Media: -8831.6
Mediana: -5483.0
Desviación Estándar: 28733.983304492558
Mínimo: -54868.0
Máximo: 27301.0

In [10]:
df.iloc[30:35]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN

In [11]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [12]:
df.loc[(df["Entity"] == "Mexico") & (df["Year"] == 2020)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [13]:
df.iloc[0:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [14]:
df.iloc[:,[0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [15]:
df.iloc[0:4,0:3]

        Entity Code  Year
0  Afghanistan  AFG  1951
1  Afghanistan  AFG  1952
2  Afghanistan  AFG  1953
3  Afghanistan  AFG  1954

# Actividad 4 - Comprobación del Entorno

In [16]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2